@echo off
echo Creating virtual environment...
py -m venv venv 
echo Activating virtual environment...
call venv\Scripts\activate.bat
echo Installing packages...
pip install flask akinator
echo Running app...
python app001.py
echo App finished executing.
pause